class DeliveryQuest < ActiveRecord::Base
  belongs_to :quest_giver, :class_name => "User" 

  # quest giver could be nil if the quest is generated by the system
  #validates :quest_giver_id, :presence => true 
  
  belongs_to :quester, :class_name => "User"
  
 # has_one :source, :class_name => "Location", :foreign_key => "location_id"
 # has_one :destination, :class_name => "Location", :foreign_key => "location_id"

  

end
